--- #YAML:1.0
name:               math-image
version:            26
abstract:           Draw some mathematical images.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bit::Vector:          0
    Compress::Zlib:       0
    constant::defer:      0
    Glib:                 1.220
    Glib::Ex::ConnectProperties:  11
    Glib::Ex::EnumBits:   11
    Glib::Ex::ObjectBits:  12
    Glib::Ex::SignalIds:  0
    Glib::Ex::SourceIds:  2
    Glib::Object::Subclass:  0
    Gtk2:                 1.220
    Gtk2::Ex::ActionTooltips:  10
    Gtk2::Ex::ComboBox::Enum:  2
    Gtk2::Ex::ComboBox::Text:  2
    Gtk2::Ex::ComboBoxBits:  2
    Gtk2::Ex::Dragger:    2
    Gtk2::Ex::GdkBits:    23
    Gtk2::Ex::NumAxis:    2
    Gtk2::Ex::Statusbar::MessageUntilKey:  11
    Gtk2::Ex::Units:      13
    Gtk2::Ex::WidgetCursor:  0
    Gtk2::Ex::WidgetEvents:  21
    Gtk2::Pango:          0
    Image::Base:          0
    Image::Base::Gtk2::Gdk::Pixbuf:  3
    Image::Base::Gtk2::Gdk::Pixmap:  2
    Image::Base::Gtk2::Gdk::Window:  2
    Image::Base::Multiplex:  0
    Image::Base::Text:    0
    List::MoreUtils:      0.24
    Locale::Messages:     0
    Locale::TextDomain:   1.19
    Math::Libm:           0
    Math::PlanePath:      0
    Math::PlanePath::Diagonals:  2
    Math::PlanePath::HeptSpiralSkewed:  4
    Math::PlanePath::HexSpiral:  9
    Math::PlanePath::HexSpiralSkewed:  9
    Math::PlanePath::MultipleRings:  7
    Math::PlanePath::PentSpiral:  4
    Math::PlanePath::PentSpiralSkewed:  3
    Math::PlanePath::PyramidRows:  4
    Math::PlanePath::PyramidSpiral:  3
    Math::PlanePath::SquareSpiral:  5
    Math::PlanePath::TheodorusSpiral:  6
    Math::PlanePath::TriangleSpiral:  3
    Math::PlanePath::TriangleSpiralSkewed:  3
    Math::Prime::XS:      0.21
    Math::TriangularNumbers:  1.012
    Module::Load:         0
    Module::Util:         0
    Number::Format:       0
    perl:                 5.008
    Scalar::Util:         1.18
    Scope::Guard:         0
    Software::License::GPL_3:  0.001
    Term::Size:           0
    Test::Weaken::Gtk2:   17
    Text::Capitalize:     0
resources:
    homepage:  http://user42.tuxfamily.org/math-image/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            Pod::Simple::HTML:  0
            warnings::unused:   0
    maximum_interoperation:
        description:  All the optional things Math-Image can use.
        requires:
            Gtk2::Ex::CrossHair:  0
            Gtk2::Ex::ErrorTextDialog::Handler:  7
            Gtk2::Ex::PodViewer:  0
            Image::Base::GD:      4
            Image::Base::PNGwriter:  2
            Image::Base::X11::Protocol::Pixmap:  0
            Image::Base::X11::Protocol::Window:  0
            Image::Xpm:           0
            Math::Aronson:        4
            Math::Symbolic:       0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            Image::Base::GD:      4
            Image::Base::PNGwriter:  2
            Image::Xpm:           0
            Parse::CPAN::Meta:    0
            Test::DistManifest:   0
            Test::Pod:            1.00
            Test::Weaken:         3
            Test::YAML::Meta:     0.15
            YAML:                 0
            YAML::Syck:           0
            YAML::Tiny:           0
            YAML::XS:             0
recommends:
    Gtk2::Ex::CrossHair:  0
    Gtk2::Ex::ErrorDialog:  7
    Gtk2::Ex::PodViewer:  0
    Image::Base:          1.09
    Image::Base::X11::Protocol::Pixmap:  0
    Image::Base::X11::Protocol::Window:  0
    Image::Xpm:           0
    Math::Aronson:        4
    Math::Symbolic:       0
