--- #YAML:1.0
name:               math-image
version:            12
abstract:           Draw some mathematical images.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Bit::Vector:          0
    constant::defer:      0
    Glib:                 0
    Glib::Ex::ConnectProperties:  7
    Glib::Ex::SignalIds:  0
    Glib::Ex::SourceIds:  2
    Glib::Object::Subclass:  0
    Gtk2:                 0
    Gtk2::Ex::Units:      0
    Gtk2::Ex::WidgetCursor:  0
    Image::Base:          0
    Image::Base::Gtk2::Gdk::Pixmap:  0
    Image::Base::Gtk2::Gdk::Window:  0
    Image::Base::Multiplex:  0
    Image::Base::Text:    0
    Lingua::EN::Numbers:  1.01
    List::MoreUtils:      0
    Locale::Messages:     0
    Locale::TextDomain:   1.19
    Math::Libm:           0
    Math::PlanePath:      2
    Math::PlanePath::HeptSpiralSkewed:  4
    Math::PlanePath::PentSpiral:  4
    Math::PlanePath::PentSpiralSkewed:  3
    Math::PlanePath::PyramidRows:  4
    Math::PlanePath::PyramidSpiral:  3
    Math::PlanePath::SquareSpiral:  5
    Math::PlanePath::TriangleSpiral:  3
    Math::PlanePath::TriangleSpiralSkewed:  3
    Math::Prime::XS:      0.20_01
    Math::TriangularNumbers:  1.012
    perl:                 5.008
    Scope::Guard:         0
    Software::License::GPL_3:  0
    Term::Size:           0
    Text::Capitalize:     0
resources:
    homepage:  http://user42.tuxfamily.org/math-image/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            Pod::Simple::HTML:  0
    maximum_interoperation:
        description:  All the optional things Math-Image can use.
        requires:
            Gtk2::Ex::CrossHair:  0
            Gtk2::Ex::ErrorTextDialog::Handler:  0
            Image::Base::GD:      4
            Image::Base::PNGwriter:  2
            Image::Base::X11::Protocol::Pixmap:  0
            Image::Base::X11::Protocol::Window:  0
            Image::Xpm:           0
            Math::Symbolic:       0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            Parse::CPAN::Meta:   0
            Test::DistManifest:  0
            Test::Pod:           1.00
            Test::Weaken:        3
            Test::YAML::Meta:    0.15
            YAML:                0
            YAML::Syck:          0
            YAML::Tiny:          0
            YAML::XS:            0
recommends:
    Gtk2::Ex::CrossHair:  0
    Gtk2::Ex::ErrorDialog:  0
    Image::Base::X11::Protocol::Pixmap:  0
    Image::Base::X11::Protocol::Window:  0
    Image::Xpm:           0
    Math::Symbolic:       0
