# Copyright 2011 Kevin Ryde

# Generated by make-oeis-catalogue.pl -- DO NOT EDIT

# This file is part of Math-Image.
#
# Math-Image is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 3, or (at your option) any later
# version.
#
# Math-Image is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with Math-Image.  If not, see <http://www.gnu.org/licenses/>.

package App::MathImage::Values::OEIS::Catalogue::Plugin::Builtin;
use strict;
use warnings;

use vars '$VERSION', '@ISA';
$VERSION = 44;
@ISA = ('App::MathImage::Values::OEIS::Catalogue::Base');

use constant info_arrayref =>
[
  {
    'class' => 'App::MathImage::Values::AbundantNumbers',
    'num' => '5101',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::All',
    'num' => '27',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Base4Without3',
    'num' => '23717',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Beastly',
    'num' => '51003',
    'parameters_hashref' => {
      'radix' => '10'
    }
  },
  {
    'class' => 'App::MathImage::Values::BinaryLengths',
    'num' => '83652',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::ChampernowneBinary',
    'num' => '30303',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::CountPrimeFactors',
    'num' => '1222',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Cubes',
    'num' => '578',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::DigitsModulo',
    'num' => '10060',
    'parameters_hashref' => {
      'radix' => '2'
    }
  },
  {
    'class' => 'App::MathImage::Values::DigitsModulo',
    'num' => '53838',
    'parameters_hashref' => {
      'radix' => '3'
    }
  },
  {
    'class' => 'App::MathImage::Values::DigitsModulo',
    'num' => '53839',
    'parameters_hashref' => {
      'radix' => '4'
    }
  },
  {
    'class' => 'App::MathImage::Values::DigitsModulo',
    'num' => '53840',
    'parameters_hashref' => {
      'radix' => '5'
    }
  },
  {
    'class' => 'App::MathImage::Values::DigitsModulo',
    'num' => '53841',
    'parameters_hashref' => {
      'radix' => '6'
    }
  },
  {
    'class' => 'App::MathImage::Values::DigitsModulo',
    'num' => '53842',
    'parameters_hashref' => {
      'radix' => '7'
    }
  },
  {
    'class' => 'App::MathImage::Values::DigitsModulo',
    'num' => '53843',
    'parameters_hashref' => {
      'radix' => '8'
    }
  },
  {
    'class' => 'App::MathImage::Values::DigitsModulo',
    'num' => '53844',
    'parameters_hashref' => {
      'radix' => '9'
    }
  },
  {
    'class' => 'App::MathImage::Values::Emirps',
    'num' => '6567',
    'parameters_hashref' => {
      'radix' => '10'
    }
  },
  {
    'class' => 'App::MathImage::Values::Even',
    'num' => '5843',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Factorials',
    'num' => '142',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Fibonacci',
    'num' => '45',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::FractionDigits',
    'num' => '21739',
    'parameters_hashref' => {
      'fraction' => '1/735',
      'radix' => '10'
    }
  },
  {
    'class' => 'App::MathImage::Values::GolayRudinShapiro',
    'num' => '22155',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::LucasNumbers',
    'num' => '204',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::MobiusFunction',
    'num' => '8683',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::NumaronsonA',
    'num' => '79000',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::ObstinateNumbers',
    'num' => '133122',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Odd',
    'num' => '5408',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Padovan',
    'num' => '931',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Palindromes',
    'num' => '6995',
    'parameters_hashref' => {
      'radix' => '2'
    }
  },
  {
    'class' => 'App::MathImage::Values::Palindromes',
    'num' => '14190',
    'parameters_hashref' => {
      'radix' => '3'
    }
  },
  {
    'class' => 'App::MathImage::Values::Palindromes',
    'num' => '14192',
    'parameters_hashref' => {
      'radix' => '4'
    }
  },
  {
    'class' => 'App::MathImage::Values::Palindromes',
    'num' => '29952',
    'parameters_hashref' => {
      'radix' => '5'
    }
  },
  {
    'class' => 'App::MathImage::Values::Palindromes',
    'num' => '29953',
    'parameters_hashref' => {
      'radix' => '6'
    }
  },
  {
    'class' => 'App::MathImage::Values::Palindromes',
    'num' => '29954',
    'parameters_hashref' => {
      'radix' => '7'
    }
  },
  {
    'class' => 'App::MathImage::Values::Palindromes',
    'num' => '29803',
    'parameters_hashref' => {
      'radix' => '8'
    }
  },
  {
    'class' => 'App::MathImage::Values::Palindromes',
    'num' => '29955',
    'parameters_hashref' => {
      'radix' => '9'
    }
  },
  {
    'class' => 'App::MathImage::Values::Palindromes',
    'num' => '2113',
    'parameters_hashref' => {
      'radix' => '10'
    }
  },
  {
    'class' => 'App::MathImage::Values::PellNumbers',
    'num' => '129',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Perrin',
    'num' => '1608',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '217',
    'parameters_hashref' => {
      'pairs' => 'first',
      'polygonal' => '3'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '290',
    'parameters_hashref' => {
      'pairs' => 'first',
      'polygonal' => '4'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '326',
    'parameters_hashref' => {
      'pairs' => 'first',
      'polygonal' => '5'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '5449',
    'parameters_hashref' => {
      'pairs' => 'second',
      'polygonal' => '5'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '1318',
    'parameters_hashref' => {
      'pairs' => 'both',
      'polygonal' => '5'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '384',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '14105',
    'parameters_hashref' => {
      'pairs' => 'second'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '566',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '567',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '1106',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '1107',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51682',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51624',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51865',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51866',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51867',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51868',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51869',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51870',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51871',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51872',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51873',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51874',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51875',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Polygonal',
    'num' => '51876',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::Primes',
    'num' => '40',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Pronic',
    'num' => '2378',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::RadixWithoutDigit',
    'num' => '32924',
    'parameters_hashref' => {
      'digit' => '0',
      'radix' => '3'
    }
  },
  {
    'class' => 'App::MathImage::Values::RadixWithoutDigit',
    'num' => '5823',
    'parameters_hashref' => {
      'digit' => '1',
      'radix' => '3'
    }
  },
  {
    'class' => 'App::MathImage::Values::RadixWithoutDigit',
    'num' => '5836',
    'parameters_hashref' => {
      'digit' => '2',
      'radix' => '3'
    }
  },
  {
    'class' => 'App::MathImage::Values::RadixWithoutDigit',
    'num' => '23705',
    'parameters_hashref' => {
      'digit' => '0',
      'radix' => '4'
    }
  },
  {
    'class' => 'App::MathImage::Values::RadixWithoutDigit',
    'num' => '23709',
    'parameters_hashref' => {
      'digit' => '1',
      'radix' => '4'
    }
  },
  {
    'class' => 'App::MathImage::Values::RadixWithoutDigit',
    'num' => '23713',
    'parameters_hashref' => {
      'digit' => '2',
      'radix' => '4'
    }
  },
  {
    'class' => 'App::MathImage::Values::RadixWithoutDigit',
    'num' => '23717',
    'parameters_hashref' => {
      'digit' => '3',
      'radix' => '4'
    }
  },
  {
    'class' => 'App::MathImage::Values::RadixWithoutDigit',
    'num' => '23721',
    'parameters_hashref' => {
      'digit' => '0',
      'radix' => '5'
    }
  },
  {
    'class' => 'App::MathImage::Values::RadixWithoutDigit',
    'num' => '23725',
    'parameters_hashref' => {
      'digit' => '1',
      'radix' => '5'
    }
  },
  {
    'class' => 'App::MathImage::Values::RadixWithoutDigit',
    'num' => '23729',
    'parameters_hashref' => {
      'digit' => '2',
      'radix' => '5'
    }
  },
  {
    'class' => 'App::MathImage::Values::RadixWithoutDigit',
    'num' => '23733',
    'parameters_hashref' => {
      'digit' => '4',
      'radix' => '5'
    }
  },
  {
    'class' => 'App::MathImage::Values::RadixWithoutDigit',
    'num' => '23737',
    'parameters_hashref' => {
      'digit' => '5',
      'radix' => '5'
    }
  },
  {
    'class' => 'App::MathImage::Values::RepdigitAnyBase',
    'num' => '53696',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Repdigits',
    'num' => '10785',
    'parameters_hashref' => {
      'radix' => '10'
    }
  },
  {
    'class' => 'App::MathImage::Values::SafePrimes',
    'num' => '5385',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::SemiPrimes',
    'num' => '1358',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::SophieGermainPrimes',
    'num' => '5384',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '4539',
    'parameters_hashref' => {
      'radix' => '2',
      'sqrt' => '2'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '4540',
    'parameters_hashref' => {
      'radix' => '3',
      'sqrt' => '2'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '4541',
    'parameters_hashref' => {
      'radix' => '4',
      'sqrt' => '2'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '4542',
    'parameters_hashref' => {
      'radix' => '5',
      'sqrt' => '2'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '2193',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '2'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '2194',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '3'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '2163',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '5'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10467',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '10'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10468',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '11'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10469',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '12'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10470',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '13'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10471',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '14'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10472',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '15'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10473',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '17'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10474',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '18'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10475',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '19'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10476',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '20'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10477',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '21'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10478',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '22'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10479',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '23'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10480',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '24'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10481',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '26'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10482',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '27'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10483',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '28'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10484',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '29'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10485',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '30'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10486',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '31'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10487',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '32'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10488',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '33'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10489',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '34'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10490',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '35'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10491',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '37'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10492',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '38'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10493',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '39'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10494',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '40'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10495',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '41'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10496',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '42'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10497',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '43'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10498',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '44'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10499',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '45'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10500',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '46'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10501',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '47'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10502',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '48'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10503',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '50'
    }
  },
  {
    'class' => 'App::MathImage::Values::SqrtDigits',
    'num' => '10504',
    'parameters_hashref' => {
      'radix' => '10',
      'sqrt' => '51'
    }
  },
  {
    'class' => 'App::MathImage::Values::Squares',
    'num' => '290',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::StarNumbers',
    'num' => '3154',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::TernaryWithout2',
    'num' => '5836',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Tetrahedral',
    'num' => '292',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Triangular',
    'num' => '217',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::Tribonacci',
    'num' => '73',
    'parameters_hashref' => {}
  },
  {
    'class' => 'App::MathImage::Values::TwinPrimes',
    'num' => '1359',
    'parameters_hashref' => {
      'pairs' => 'first'
    }
  },
  {
    'class' => 'App::MathImage::Values::TwinPrimes',
    'num' => '6512',
    'parameters_hashref' => {
      'pairs' => 'second'
    }
  },
  {
    'class' => 'App::MathImage::Values::TwinPrimes',
    'num' => '1097',
    'parameters_hashref' => {
      'pairs' => 'both'
    }
  }
]
;
1;
__END__
